version: '3.8'
  
services:
  gateway_service:
    container_name: gateway_service
    build:
      context: ./
      dockerfile: api_gateway_service/Dockerfile
    command: ./api_gateway_service/bin/main 
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - auth_service
    environment:
      - CONFIG_GATEWAY_PATH=./api_gateway_service/configs/config.yaml
    networks:
      - microservices

  auth_service:
    container_name: auth_service
    build:
      context: ./
      dockerfile: auth_service/Dockerfile
    command: ./auth_service/bin/main && migrate -database postgres://postgres:secret@localhost:5432/postgres?sslmode=disable -path auth_service/migrations up
    restart: always
    ports:
      - 44044:44044
    depends_on:
      - postgres_dbauth
    environment:
      - DB_PASSWORD=secret
      - CONFIG_AUTH_PATH=./auth_service/configs/config.yaml
    networks:
      - microservices
      
  postgres_dbauth:
    restart: always
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DBNAME=postgres
    networks:
      - microservices 

networks:
  microservices:
    name: microservices
 