version: '3.8'
  
services:
  unimatch:
    build: ./
    command: ./api_gateway_service/bin/main && ./auth_service/bin/main
    ports:
      - 8080:8080
    depends_on:
      - postgres_dbauth
    environment:
      - DB_PASSWORD=secret
      - CONFIG_PATH=./config/config.yaml
  postgres_dbauth:
    restart: always
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DBNAME=postgres
    
    

  

  
  